#!/bin/bash

##### Aliases #####
alias g=git
alias ls='ls -G'
alias errcho='>&2 echo'  # echo to stderr
alias reload='source ${HOME}/.profile'
alias dm=docker-machine
alias delpyc='find . -iname "*.pyc" -delete && find . -iname "__pycache__" -delete'
alias delorig='find . -iname "*.orig" -delete'
alias custom_commands='grep -e ".*() {" ~/bin/* | cut -d ":" -f2 | cut -d "("  -f1'
# These aliases have to be defined before all the scripts in bin are loaded.

# These variables are used in other scripts, we have to make them known in the system.
export WD=${HOME}/projects
export PROJECTS=`ls -d ${WD}/*`

# Lazy "cd" alias
for project in ${PROJECTS}
do
    alias `echo ${project} | rev | cut -d "/" -f1 | rev`="cd ${WD}/${project}"
done

##### The lazy programmer bash functions #####
# Include own scripts on the path
for f in ${HOME}/bin/*.sh; do
   . ${f}
done


# No duplicated lines on bash_history
export HISTCONTROL=ignoredups

##### GIT autocompletion #####
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

##### Virtualenv wrapper #####
source /usr/local/bin/virtualenvwrapper.sh

[[ -s "${HOME}/.gvm/scripts/gvm" ]] && source "${HOME}/.gvm/scripts/gvm" && gvm use go1.6 > /dev/null
export GO15VENDOREXPERIMENT=0
export GOPATH=${WD}/go
