#!/bin/bash

##### Aliases #####
# These aliases have to be defined before the scripts in ~/bin are loaded.
alias g=git
alias gf='git fetch -p'
alias gp='git pull --rebase'
alias ls='ls -G'
alias errcho='>&2 echo'  # echo to stderr
alias reload='source ${HOME}/.profile'
alias dc=docker-compose
alias delpyc='find . -iname "*.pyc" -delete && find . -iname "__pycache__" -delete'
alias delorig='find . -iname "*.orig" -delete'
alias custom_commands='grep -e ".*() {" ~/bin/* | cut -d ":" -f2 | cut -d "("  -f1'

# These variables are used in other scripts, so they have to be exported.
export WD=${HOME}/projects
export PROJECTS=`ls -d ${WD}/*`

# Lazy "cd" alias to repositories
for project in ${PROJECTS}
do
    alias `echo ${project} | rev | cut -d "/" -f1 | rev`="cd ${project}"
done

##### The lazy programmer bash functions #####
# Include own scripts on the session
for f in ${HOME}/bin/*.sh; do
   . ${f}
done

# No duplicated lines on bash_history
export HISTCONTROL=ignoredups

##### GIT autocompletion #####
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Setting up pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; pyenv virtualenvwrapper; fi
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"

##### Ruby version manager #####
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
